version: '3.8'

services:
  postgres:
    container_name: pbd_estudo_de_caso_1_postgres
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pbd_estudo_de_caso_1_db
    ports:
      - "6754:5432"
    volumes:
      - pbd_estudo_de_caso_1_postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pbd_estudo_de_caso_1_pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "6755:80"
    volumes:
      - pbd_estudo_de_caso_1_pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  pbd_estudo_de_caso_1_postgres_data:
  pbd_estudo_de_caso_1_pgadmin_data:
